### ISSUE TITLE
permutedims

### ISSUE THREAD

**Issue by LaurentPlagne** [JuliaComputing/ArrayFire.jl#126]
Hi again,

I have a problem when trying to permute 3D arrays with ArrayFire.jl
`afx` is an `AFArray` of size (400,200,300)
`afy` is an `AFArray` of size (200,300,400)
`circperm=[2,3,1]`

The normal `permutedims` method modifies the input parameter `cirperm`
`afy=ArrayFire.permutedims(afx,circperm)`

`circperm` is then  modified to `[2,3,1,4]`

I guess that it is unexpected...

I also tried to figure out how to write an inplace version of `permutedims!` but it seems that the arrayfire `reorder` method does not perform the task in place anyway...

I also experience a problem with the garbage collector.
The following loop will fail ("out of device memory") if I omit to call the gc (last line).
When I apply the gc() it is ok but the performance gets lower...

`for i in 1:nsteps`  
    ` afy=ArrayFire.permutedims(afx,circperm)`
    `  afz=ArrayFire.permutedims(afy,circperm)`
    `  afx=ArrayFire.permutedims(afz,circperm)`
    `  gc()`
  `end`

Is there a way to let the arrays afx,afy,afz on the device during such a loop (using arrayfire)?

Thank you for your help

**Comment by ranjanan** [comment]
@LaurentPlagne forgive me for taking some time to get to this. I was on travel. 

>I guess that it is unexpected...

You are right. Internally, I'm modifying the `circperm` array so I don't create a new `circperm` array every single time you call the function  `permutedims`. If you would like an in place version of `permutedims`, you could post an issue [here](http://www.github.com/arrayfire/arrayfire/issues/) because I don't think you can implement one just purely using the functionality of this wrapper. 

As for the `gc` issue, currently you need to manually trigger the `gc()` if you want to limit your memory allocation. Please refer to issue #27 for details on the challenges.

**Comment by LaurentPlagne** [comment]
Thank you very much for your detailed answer !

I try to translate (from C++) a HPC solver involving successive dim permutations, both in native Julia and in Julia+GPU. For out-of-cache arrays, the native Julia permutedims! performance s OK (single thread) at about 4GB/s. Because of the missing in place version, ArrayFire is not ;)
I obtain around 3GB/s, while a naïve OpenCl version (via OpenCL.jl) is about 70 GB/s and an optimized OpenCL can exceed 120 GB/s...

I am currently discovering the different options to produce efficient computations through Julia and it is a bit early to claim for new features to be included in ArrayFire ;) 

Thank you again.
Laurent
