### ISSUE TITLE
digamma and trigamma functions

### ISSUE THREAD

**Issue by esproff** [JuliaComputing/ArrayFire.jl#55]
Does anyone know if the digamma and trigamma functions will ever be implemented?

I fear this might be something which has to be handled by the original ArrayFire and not just by the wrapper, but I thought I'd ask since I've been unable able to design a sufficiently efficient workaround.

**Comment by kmsquire** [comment]
@esproff, until they're implemented here, you can just use the versions in base Julia, right?  Although you did suggest that you probably want something more efficient.

Since this project, like most of the Julia ecosystem, is open source and volunteer based, your best chance to having those implemented would be to look into it yourself, or at a minimum, turn your question into a request.  Usually these things are implemented by someone who has a need for them.

That said, it certainly would be a lot easier to support here if ArrayFire itself already had them.  Why don't you create an issue there?  https://github.com/arrayfire/arrayfire/issues

Cheers!

**Comment by esproff** [comment]
@kmsquire, ok thanks for the timely response, I posted the issue to the primary repo.

**Comment by ranjanan** [comment]
@kmsquire Thanks!
